### ISSUE TITLE
Error on build - 'rm' is not recognized

### ISSUE THREAD

**Issue by erikadanis81** [jhades/angular2-library-example#4]
here is the npm-debug.log on a Windows 10 environment.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\danise\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--color=always' ]
2 info using npm@3.10.8
3 info using node@v4.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle angular2-library-example@1.0.6~prebuild: angular2-library-example@1.0.6
6 silly lifecycle angular2-library-example@1.0.6~prebuild: no script for prebuild, continuing
7 info lifecycle angular2-library-example@1.0.6~build: angular2-library-example@1.0.6
8 verbose lifecycle angular2-library-example@1.0.6~build: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-library-example@1.0.6~build: PATH: C:\Users\danise\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Dev\ApplicationPlatform-CoreUI\TypeScriptHTMLApp1\node_modules.bin;C:\Program Files\nodejs;.\node_modules.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Seq\;C:\Program Files\Redis\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\danise\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
10 verbose lifecycle angular2-library-example@1.0.6~build: CWD: C:\Dev\ApplicationPlatform-CoreUI\TypeScriptHTMLApp1
11 silly lifecycle angular2-library-example@1.0.6~build: Args: [ '/d /s /c', 'rm -rf lib && tsc -p src' ]
12 silly lifecycle angular2-library-example@1.0.6~build: Returned: code: 1  signal: null
13 info lifecycle angular2-library-example@1.0.6~build: Failed to exec build script
14 verbose stack Error: angular2-library-example@1.0.6 build: `rm -rf lib && tsc -p src`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\danise\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\danise\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-library-example@1.0.6
16 verbose cwd C:\Dev\ApplicationPlatform-CoreUI\TypeScriptHTMLApp1
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\danise\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build" "--color=always"
19 error node v4.6.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular2-library-example@1.0.6 build: `rm -rf lib && tsc -p src`
22 error Exit status 1
23 error Failed at the angular2-library-example@1.0.6 build script 'rm -rf lib && tsc -p src'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-library-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rm -rf lib && tsc -p src
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-library-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-library-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by josefromsanjose** [comment]
any word on this. I am having the same issue.

**Comment by shaikhspear16** [comment]
rm is not recognised on windows , its linux/osx command (not sure). Use rimraf instead as the latest quickstart uses.
rm is basically used to remove a directory, just like mkdir is used to create one!!
