### ISSUE TITLE
EXCEMPTION: No Directive annotation found on HelloWorld

### ISSUE THREAD

**Issue by xaun** [jhades/angular2-library-example#5]
When trying to run the webpack example:

```
browser_adapter.js:76Error: No Directive annotation found on HelloWorld
    at new BaseException (http://localhost:8080/bundle.js:11843:24)
    at DirectiveResolver.resolve (http://localhost:8080/bundle.js:26067:16)
    at RuntimeMetadataResolver.getMetadata (http://localhost:8080/bundle.js:39340:52)
    at http://localhost:8080/bundle.js:39383:63
    at Array.map (native)
    at RuntimeMetadataResolver.getViewDirectivesMetadata (http://localhost:8080/bundle.js:39383:28)
    at RuntimeCommandFactory.componentTemplateFactory (http://localhost:8080/bundle.js:34801:71)
    at RuntimeCommandFactory.createBeginComponent (http://localhost:8080/bundle.js:36900:44)
    at CommandBuilderVisitor.visitElement (http://localhost:8080/bundle.js:37007:51)
    at ElementAst.visit (http://localhost:8080/bundle.js:36043:25)
```

**Comment by hakkurishian** [comment]
I pulled the branch from @kirjs 
 https://github.com/kirjs/angular2-library-example (open pull request)
Then removed directives: [HelloWorld], from the import of the example and it works !

**Comment by kirjs** [comment]
@jhades Any plans on merging the PR?
I understand things can get busy for you, let's discuss?
I'm happy to look into upgrading  to the latest angular version as well.

**Comment by jhades** [comment]
Hello @kirjs, I have just merged the pull request, apologies for the delay. It would be great to have the latest upgrade if you have the time, please cc me here on Github because somehow I don't get notified when a PR is available. Or contact me at admin@angular-university.io, again thanks for the PR
